### ISSUE TITLE
DÚVIDAS NA UTILIZAÇÃO

### ISSUE THREAD

**Issue by thaynanlima** [mrprompt/ponto-noserver#1]
Amigo, primeiro, parabéns pelo trabalho!

Estou interessado em usar a ferramenta para uso pessoal.
Fiz a "instalação" num servidor apache local para testar o funcionamento, mas o sistema já abre na tela de login.

Como faço o meu cadastro como funcionário e quais as instruções básicas para fazer o sistema funcionar? (Pretendo pôr o sistema online no meu server).

Se puder, me responde no email thaynanlimamusic@gmail.com
Te agradeço.

**Comment by mrprompt** [comment]
Salve @thaynanlima obrigado :)
Te recomendo utilizar a dupla `ponto-api` e `ponto-cliente`, esse projeto aqui não foi finalizado e foi só um experimento.
No projeto de API, você pode ver no código o usuário inicial criado e sua senha, depois, é só ir adicionando mais.
Qualquer dúvida, só falar.
